### ISSUE TITLE
命令执行遇到问题

### ISSUE THREAD

**Issue by bmers** [Jun10ng/ebpf-docker-for-desktop#1]
你好，首先感谢你的分享！我在执行你给的命令时，遇到了些问题：
在执行 

```dockerfile
docker build -t ebpf:v1 .
```

时Run到Dockerfile中的

```dockerfile
RUN sh /root/linuxkit-complier.sh
```

遇到如下报错：

> ERROR [stage-1 12/14] RUN sh /root/linuxkit-complier.sh   0.3s
> [stage-1 12/14] RUN sh /root/linuxkit-complier.sh:
> #18 0.315 coping file to source/
> : not foundroot/linuxkit-complier.sh: 3:
> #18 0.316 cp: cannot stat '/usr/src/5.10.16.3-microsoft-standard-WSL2/': No such file or directory
> #18 0.317 mv: cannot stat '5.10.16.3-microsoft-standard-WSL2': No such file or directory
> : not foundroot/linuxkit-complier.sh: 7:
> #18 0.317 coping file to build/
> #18 0.318 cp: cannot stat '/usr/src/5.10.16.3-microsoft-standard-WSL2/': No such file or directory
> #18 0.319 mv: cannot stat '5.10.16.3-microsoft-standard-WSL2': No such file or directory
> : not foundroot/linuxkit-complier.sh: 11:
> : not foundroot/linuxkit-complier.sh: 13:
> #18 0.319 creating config file
> #18 0.320 /root/linuxkit-complier.sh: 15: cd: can't cd to /usr/src/5.10.16.3-microsoft-standard-WSL2
> #18 0.320 make: *** No rule to make target 'menuconfig'.  Stop.
> '.  Stop. make: *** No rule to make target 'defconfig
> : not foundroot/linuxkit-complier.sh: 18:
> : not foundroot/linuxkit-complier.sh: 26:
> : not foundroot/linuxkit-complier.sh: 27:
> #18 0.322 preparing
> '.  Stop. make: *** No rule to make target 'prepare
> : not foundroot/linuxkit-complier.sh: 30:
> : not foundroot/linuxkit-complier.sh: 31: bash
> : not foundroot/linuxkit-complier.sh: 32:
> executor failed running [/bin/sh -c sh /root/linuxkit-complier.sh]: exit code: 127

请问你是否遇到类似问题，知道该如何解决吗？谢谢

**Comment by Jun10ng** [comment]
好的，我检查下。
请问你是用win还是mac

**Comment by bmers** [comment]
win10



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月21日(周一) 中午11:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jun10ng/ebpf-docker-for-desktop] 命令执行遇到问题 (Issue #1)




 
好的，我检查下。
 请问你是用win还是mac
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Jun10ng** [comment]
> win10
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年2月21日(周一) 中午11:44 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Jun10ng/ebpf-docker-for-desktop] 命令执行遇到问题 (Issue #1) 好的，我检查下。 请问你是用win还是mac — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;



看起来是路径不存在。

“/root/linuxkit-dl.sh" 这个shell 脚本有被执行吗？在脚本内，我写了创建路径的代码。
<img width="836" alt="image" src="https://user-images.githubusercontent.com/46768176/154886474-6ade8961-e79d-40b9-aea4-28bc907203fa.png">

可以在容器内跑下
```
sh /root/linuxkit-dl.sh
sh /root/linuxkit-complier.sh
```

**Comment by bmers** [comment]
> > win10
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年2月21日(周一) 中午11:44 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [Jun10ng/ebpf-docker-for-desktop] 命令执行遇到问题 (Issue #1) 好的，我检查下。 请问你是用win还是mac — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 看起来是路径不存在。
> 
> “/root/linuxkit-dl.sh" 这个shell 脚本有被执行吗？在脚本内，我写了创建路径的代码。 <img alt="image" width="836" src="https://user-images.githubusercontent.com/46768176/154886474-6ade8961-e79d-40b9-aea4-28bc907203fa.png">
> 
> 可以在容器内跑下
> 
> ```
> sh /root/linuxkit-dl.sh
> sh /root/linuxkit-complier.sh
> ```

**Comment by bmers** [comment]
> > win10
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年2月21日(周一) 中午11:44 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [Jun10ng/ebpf-docker-for-desktop] 命令执行遇到问题 (Issue #1) 好的，我检查下。 请问你是用win还是mac — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 看起来是路径不存在。
> 
> “/root/linuxkit-dl.sh" 这个shell 脚本有被执行吗？在脚本内，我写了创建路径的代码。 <img alt="image" width="836" src="https://user-images.githubusercontent.com/46768176/154886474-6ade8961-e79d-40b9-aea4-28bc907203fa.png">
> 
> 可以在容器内跑下
> 
> ```
> sh /root/linuxkit-dl.sh
> sh /root/linuxkit-complier.sh
> ```

从执行过程看 linuxkit-dl.sh 是执行到了。
```
#14 [stage-1  8/14] COPY linuxkit-dl.sh /root
#14 sha256:62c4f7d896261f770de88e51be93c9c9bb2e8d9516da379f4b356fff880380f0
#14 CACHED

#17 [stage-1 11/14] RUN echo "download success"
#17 sha256:59a45cd4caba8218609386bbbc3bf1de78f833e0e507032d71195e2b76f1f711
#17 CACHED

#18 [stage-1 12/14] RUN sh /root/linuxkit-complier.sh
#18 sha256:7c9ad38e1dbd75839f24ae75708f84f097b3745161dd45af3bb87078901d9e50
#18 0.356 coping file to source/
: not foundroot/linuxkit-complier.sh: 3:
#18 0.364 cp: cannot stat '/usr/src/5.10.16.3-microsoft-standard-WSL2/': No such file or directory
```

不好意思对docker还不是很熟，docker编译没有成功，并没有ebpf这个镜像生成，该怎么进去容器？
![image](https://user-images.githubusercontent.com/29788896/154891104-81cbc58c-beb8-40b8-b459-be40ba35a3d5.png)

**Comment by Jun10ng** [comment]
> > > win10
> > > […](#)
> > > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年2月21日(周一) 中午11:44 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [Jun10ng/ebpf-docker-for-desktop] 命令执行遇到问题 (Issue #1) 好的，我检查下。 请问你是用win还是mac — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> > 
> > 
> > 看起来是路径不存在。
> > “/root/linuxkit-dl.sh" 这个shell 脚本有被执行吗？在脚本内，我写了创建路径的代码。 <img alt="image" width="836" src="https://user-images.githubusercontent.com/46768176/154886474-6ade8961-e79d-40b9-aea4-28bc907203fa.png">
> > 可以在容器内跑下
> > ```
> > sh /root/linuxkit-dl.sh
> > sh /root/linuxkit-complier.sh
> > ```
> 
> 从执行过程看 linuxkit-dl.sh 是执行到了。
> 
> ```
> #14 [stage-1  8/14] COPY linuxkit-dl.sh /root
> #14 sha256:62c4f7d896261f770de88e51be93c9c9bb2e8d9516da379f4b356fff880380f0
> #14 CACHED
> 
> #17 [stage-1 11/14] RUN echo "download success"
> #17 sha256:59a45cd4caba8218609386bbbc3bf1de78f833e0e507032d71195e2b76f1f711
> #17 CACHED
> 
> #18 [stage-1 12/14] RUN sh /root/linuxkit-complier.sh
> #18 sha256:7c9ad38e1dbd75839f24ae75708f84f097b3745161dd45af3bb87078901d9e50
> #18 0.356 coping file to source/
> : not foundroot/linuxkit-complier.sh: 3:
> #18 0.364 cp: cannot stat '/usr/src/5.10.16.3-microsoft-standard-WSL2/': No such file or directory
> ```
> 
> 不好意思对docker还不是很熟，docker编译没有成功，并没有ebpf这个镜像生成，该怎么进去容器？ ![image](https://user-images.githubusercontent.com/29788896/154891104-81cbc58c-beb8-40b8-b459-be40ba35a3d5.png)

我更新了下complier脚本，里面会新建文件夹，你重新run一下看看。
这个命令可以删除缓存
```
docker builder prune 
```

**Comment by bmers** [comment]
感谢回复，docker编译的问题，我换了台机子编译通过了（原来那台机子还是不ok）。在编译ok的机子上，执行demo时，遇到头文件找不到问题
```
python3 hello.py 
In file included from <built-in>:1:
././include/linux/kconfig.h:7:10: fatal error: 'generated/autoconf.h' file not found
#include <generated/autoconf.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/root/example/hello.py", line 6, in <module>
    b = BPF(src_file="hello.c")
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 364, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module b'hello.c'
```
类似问题是否有遇见过呢？手动执行linuxkit-complier.sh脚本后，还是一样报错。

**Comment by bmers** [comment]
在/usr/src/$(uname -r)目录下，执行命令make -r menuconfig
有如下报错
```
make -r menuconfig
*
* Unable to find the ncurses package.
* Install ncurses (ncurses-devel or libncurses-dev
* depending on your distribution).
*
* You may also need to install pkg-config to find the
* ncurses installed in a non-default location.
*
make[1]: *** [scripts/kconfig/Makefile:214: scripts/kconfig/mconf-cfg] Error 1
make: *** [Makefile:603: menuconfig] Error 2
```

**Comment by Jun10ng** [comment]
"././include/linux/kconfig.h:7:10: fatal error: 'generated/autoconf.h' file not found" 
这个问题我遇到过，就是通过linuxkit-complier.sh要解决的。



> 在/usr/src/$(uname -r)目录下，执行命令make -r menuconfig 有如下报错
> 
> ```
> make -r menuconfig
> *
> * Unable to find the ncurses package.
> * Install ncurses (ncurses-devel or libncurses-dev
> * depending on your distribution).
> *
> * You may also need to install pkg-config to find the
> * ncurses installed in a non-default location.
> *
> make[1]: *** [scripts/kconfig/Makefile:214: scripts/kconfig/mconf-cfg] Error 1
> make: *** [Makefile:603: menuconfig] Error 2
> ```

这样来看，应该是你安装的linux发行版缺少了一下几个包，导致linuxkit-complier.sh 无法编译

**Comment by bmers** [comment]
> "././include/linux/kconfig.h:7:10: fatal error: 'generated/autoconf.h' file not found" 这个问题我遇到过，就是通过linuxkit-complier.sh要解决的。
> 
> > 在/usr/src/$(uname -r)目录下，执行命令make -r menuconfig 有如下报错
> > ```
> > make -r menuconfig
> > *
> > * Unable to find the ncurses package.
> > * Install ncurses (ncurses-devel or libncurses-dev
> > * depending on your distribution).
> > *
> > * You may also need to install pkg-config to find the
> > * ncurses installed in a non-default location.
> > *
> > make[1]: *** [scripts/kconfig/Makefile:214: scripts/kconfig/mconf-cfg] Error 1
> > make: *** [Makefile:603: menuconfig] Error 2
> > ```
> 
> 这样来看，应该是你安装的linux发行版缺少了一下几个包，导致linuxkit-complier.sh 无法编译

apt-get install ncurses-dev,对应缺失包，安装上了~进入了内核配置界面了
![image](https://user-images.githubusercontent.com/29788896/155058323-9576fcb1-d783-4ea4-9285-7c95554cc5e8.png)

**Comment by bmers** [comment]
这个配置页面该选择什么继续下去？

**Comment by Jun10ng** [comment]
我查阅了[资料](https://askubuntu.com/questions/270381/how-do-i-install-ncurses-header-files)，似乎比较多人说要安装libncurses-dev 而不是 ncurses-dev

**Comment by bmers** [comment]
emmmmm，it not wokrs,即使安装了libncurses-dev，还是找不到autoconf.h
```
python3 hello.py 
In file included from <built-in>:1:
././include/linux/kconfig.h:7:10: fatal error: 'generated/autoconf.h' file not found
#include <generated/autoconf.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/root/example/hello.py", line 6, in <module>
    b = BPF(src_file="hello.c")
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 364, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module b'hello.c'
```

可能是我WSL2的内核版本不匹配？
```
root@8fb39f46b127:~/example# uname -r
4.19.104-microsoft-standard
```
我不太理解，这个版本是否也需要5.10？
update:将WSL2内核版本更新到5.10.16.3-microsoft-standard-WSL2，依然同样问题

**Comment by bmers** [comment]
问题已解决，'generated/autoconf.h' file not found，遇到这个问题是因为，该文件是在make -r prepare之后生成在/usr/src/linux-headers-5.10.76-linuxkit/include下，而此时/usr/src/$(uname -r)/source /usr/src/$(uname -r)/build 对应目录下并没有更新。
所以只需要删除/usr/src/$(uname -r)/source /usr/src/$(uname -r)/build后,重新cp即可
```
cd /lib/modules/$(uname -r)
rm -rf source
rm -rf build
mkdir -p /usr/src/$(uname -r)/
cp -r /usr/src/$(uname -r)/ .
mv $(uname -r) source

echo "coping file to build/"
cp -r /usr/src/$(uname -r)/ .
mv $(uname -r) build
```
![image](https://user-images.githubusercontent.com/29788896/155132922-364dd8ce-a598-4257-89f4-fc30f2c7afee.png)
跑出hello world真不容易
吃了不懂docker和不懂内核编译的亏.....
